TravelAgency.Web/Controllers/BookingsController.cs
// Developer: Hoora


using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Xml.Linq;
using TravelAgency.BLL.Interfaces;
using TravelAgency.Lib.Models;
using TravelAgency.Web.ViewModel.Bookings;

namespace TravelAgency.Web.Controllers
{
    public class BookingsController : Controller
    {
        private readonly IBookingRepository _bookingRepository;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public BookingsController(IBookingRepository bookingRepository, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _bookingRepository = bookingRepository;
            _userManager = userManager;
            _signInManager = signInManager;
        }



        // GET: BookingsController
        public async Task<ActionResult> Index()
        {
            if (!_signInManager.IsSignedIn(User))
                return RedirectToAction("Login", "Account");
            var userId = _userManager.GetUserId(User);
            int Id = Convert.ToInt32(userId);
            try
            {
                IList<Booking> bookings = await _bookingRepository.GetAllBookingsByCstmrID(Id);
                IList<BookingIndexViewModel> bookingListVM = new List<BookingIndexViewModel>();

                foreach (var item in bookings)
                {
                    BookingIndexViewModel bookingVM = new BookingIndexViewModel();
                    Booking booking = new Booking();
                    BookingDetail bookingDetail = new BookingDetail();

                    bookingVM.Booking = booking;
                    bookingVM.BookingDetail = bookingDetail;
                    
                    bookingVM.Booking.BookingDate = item.BookingDate;
                    bookingVM.Booking.BookingNo = item.BookingNo;
                    bookingVM.Booking.TravelerCount = item.TravelerCount;

                    TripType tripType = new TripType();
                    tripType.Ttname = item.TripType.Ttname;
                    bookingVM.Booking.TripType = tripType;

                    Package package = new Package();
                    package.PkgName = item.Package == null ? "" : item.Package.PkgName;
                    bookingVM.Booking.Package = package;

                    BookingDetail bookingDetails1 = new BookingDetail();
                    if (item.BookingDetails.Count != 0)
                    {
                        bookingDetails1 = item.BookingDetails.ToList()[0];

                        bookingVM.BookingDetail.ItineraryNo = bookingDetails1.ItineraryNo;
                        bookingVM.BookingDetail.TripStart = bookingDetails1.TripStart;
                        bookingVM.BookingDetail.TripEnd = bookingDetails1.TripEnd;
                        bookingVM.BookingDetail.Description = bookingDetails1.Description;
                        bookingVM.BookingDetail.Destination = bookingDetails1.Destination;
                        bookingVM.BookingDetail.BasePrice = bookingDetails1.BasePrice;
                        bookingVM.BookingDetail.AgencyCommission = bookingDetails1.AgencyCommission;

                        Region region = new Region();
                        region.RegionName = bookingDetails1.Region.RegionName;
                        bookingVM.BookingDetail.Region = region;

                        Fee fee = new Fee();
                        fee.FeeName = bookingDetails1.Fee.FeeName;
                        bookingVM.BookingDetail.Fee = fee;

                        Class @class = new Class();
                        @class.ClassName = bookingDetails1.Class.ClassName;
                        bookingVM.BookingDetail.Class = @class;
                    }
                    else
                    {
                        bookingVM.BookingDetail.ItineraryNo = null;
                        bookingVM.BookingDetail.TripStart = null;
                        bookingVM.BookingDetail.TripEnd = null;
                        bookingVM.BookingDetail.Description = "";
                        bookingVM.BookingDetail.Destination = "";
                        bookingVM.BookingDetail.BasePrice = null;
                        bookingVM.BookingDetail.AgencyCommission = null;

                        Region region = new Region();
                        region.RegionName = "";
                        bookingVM.BookingDetail.Region = region;

                        Fee fee = new Fee();
                        fee.FeeName = "";
                        bookingVM.BookingDetail.Fee = fee;

                        Class @class = new Class();
                        @class.ClassName = "";
                        bookingVM.BookingDetail.Class = @class;
                    }

                    bookingListVM.Add(bookingVM);

                }
                return View(bookingListVM);
            }
            catch (Exception)
            {
                return View();
            }
        }



        // GET: BookingsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookingsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookingsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookingsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BookingsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookingsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BookingsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TravelAgency.Web/Controllers/ContactUsController.cs
// Developer: Jashish


using Microsoft.AspNetCore.Mvc;
using System.Xml.Linq;
using TravelAgency.BLL.Interfaces;
using TravelAgency.Lib.Created_Models;
using TravelAgency.Web.ViewModel.Agents;

namespace TravelAgency.Web.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly IAgentDetsRepository _agentRepo;

        public ContactUsController(IAgentDetsRepository agentRepo)
        {
            _agentRepo = agentRepo;
        }



        // GET: AgentsController
        public async Task<ActionResult> Index()
        {
            try
            {
                IList<AgentDetails> agentsInfo= _agentRepo.getAllAgentDetails();
                IList<AgentIndexVM> agentsListVM = new List<AgentIndexVM>();

                foreach (var item in agentsInfo)
                {
                    AgentIndexVM agentsVM = new AgentIndexVM()
                    {
                        agentInfo = item
                    };

                    agentsListVM.Add(agentsVM);

                }
                return View(agentsListVM);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }
        }



        // GET: BookingsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookingsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookingsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookingsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BookingsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookingsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BookingsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TravelAgency.Web/Controllers/PackagesController.cs
// Developer: Jashish


using Microsoft.AspNetCore.Mvc;
using System.Xml.Linq;
using TravelAgency.BLL.Interfaces;
using TravelAgency.Lib.Models;
using TravelAgency.Web.ViewModel.Packages;

namespace TravelAgency.Web.Controllers
{
    public class PackagesController : Controller
    {
        private readonly IPackageRepository _PackageRepository;

        public PackagesController(IPackageRepository PackageRepository)
        {
            _PackageRepository = PackageRepository;
        }



        // GET: PackagesController
        public async Task<ActionResult> Index()
        {
            try
            {
                IList<Package> Packages = await _PackageRepository.GetAllPackages();
                IList<PackageIndexVM> PackageListVM = new List<PackageIndexVM>();

                foreach (var item in Packages)
                {
                    decimal base_p = item.PkgBasePrice;
                    decimal agency_p = item.PkgAgencyCommission ?? 0;
                    // Making sure user is never surprised
                    decimal total_price = Math.Round(base_p + agency_p, 2, MidpointRounding.AwayFromZero);

                    PackageIndexVM PackageVM = new PackageIndexVM()
                    {
                        PkgName = item.PkgName,
                        PkgDesc = item.PkgDesc,
                        PkgStartDate = item.PkgStartDate,
                        PkgEndDate = item.PkgEndDate,
                        //Putting only 2 decimal places
                        PkgTotPrice = "$ "+total_price.ToString("N2"),
                    };
                    PackageListVM.Add(PackageVM);

                }
                return View(PackageListVM);
            }
            catch (Exception)
            {
                return View();
            }
        }



        //// GET: PackagesController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: PackagesController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: PackagesController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: PackagesController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: PackagesController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: PackagesController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: PackagesController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

TravelAgency.Web/Views/Shared/_Layout.cshtml
@* Developer: Hoora *@


@inject SignInManager<IdentityUser> _signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    </environment>

    <environment exclude="Development">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="abbsolute"
              asp-suppress-fallback-integrity="true">
    </environment>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container-fluid">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #811700;">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png" asp-append-version="true" width="200">
                    </a>
                    <button class="navbar-toggler" type="button" style="background-color: white;" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Index" style="font-size: 18px; font-weight: bold;">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="ContactUs" asp-action="Index" style="font-size: 18px; font-weight: bold;">Contact Us</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Packages" asp-action="Index" style="font-size: 18px; font-weight: bold;">Packages</a>
                            </li>
                           
                            @if (_signInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Bookings" asp-action="Index" style="font-size: 18px; font-weight: bold;">Bookings</a>
                                </li>
                            }
                        </ul>

                        <ul class="navbar-nav me-auto">
                            @if (_signInManager.IsSignedIn(User))
                            {
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" class="nav-link btn btn-link text-white fw-bold">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white fw-bold" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-white fw-bold" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    </div>


    <div class="container-fluid" d-flex flex-column">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="fixed-bottom container-fluid">
        <footer style="background-color: #333; color: #fff; padding: 20px; text-align: center;">

            <div class="container">
                &copy; 2023 - TravelExperts.Web
                @* - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
            </div>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>